# CI config

# shared key for the python jobs to not have redundant config parameters
# PROJECT, TESTSDIR, SRCDIR are used in the tox.ini
# cp -no-clobber copies files but doesn't overwrite existing ones (e.g. sonar property settings)
.python_defaults: &py_anchor  # using anchor magic
  image: registry.gitlab.semanticlab.net/docker/py3base:3.12
  before_script:
    - export TESTSDIR=src/python/weblyzard_api/tests/always_run/
    - git submodule sync --recursive
    - git submodule update --init --recursive --remote
    - rsync -av --exclude='README.md' --exclude='.git' wl_python_utils/ .
    - uv tool install pyproject-parser[cli]
    - sed -i s/-dev/".$(date +%Y%m%d.%H%M)"/g pyproject.toml
    - export PATH="~/.local/bin:$PATH"
    - export PROJECT=`pyproject-info project.name | xargs`
    - if test -f "version.txt"; then cat version.txt; else pyproject-info project.version | xargs > version.txt; fi
    - export VERSION=`cat version.txt`
    - echo $PROJECT
    - echo $VERSION


stages:
  - test-python
  - test-java
  - deploy
  - build-package

pytest:
  <<: *py_anchor  # we reference the anchor here
  stage: test-python
  only:
    - branches
  script:
    - export UV_INDEX_WLT_NEXUS_USERNAME=${NEXUS_USER}
    - export UV_INDEX_WLT_NEXUS_PASSWORD=${NEXUS_PW}
    - uv sync --index-strategy unsafe-best-match
    - uv run pytest ${TESTSDIR}
    - PROJECT=${PROJECT} VERSION=${VERSION} sonar-scanner -D sonar.host.url=${sonarhost}  -D sonar.login=${sonarlogin}
  tags:
    - backend-runner
  artifacts:
    paths:
      - version.txt
    expire_in: 4 weeks

pylint:
  <<: *py_anchor
  stage: test-python
  only:
    - branches
  script:
    - tox -q -e pylint
  when: manual

vulture:
  <<: *py_anchor
  stage: test-python
  only:
    - branches
  script:
    - tox -q -e vulture
  when: manual


job_build_package:
  stage: build-package
  rules:
    - if: $CI_COMMIT_TAG # Run this job when a tag is created
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE == "push" # or on push to master
  script:
    - export UV_INDEX_WLT_NEXUS_USERNAME=${NEXUS_USER}
    - export UV_INDEX_WLT_NEXUS_PASSWORD=${NEXUS_PW}
    - echo "Running build package job for tag $CI_COMMIT_TAG"
    - make build
  tags:
    - backend-runner
  when: manual



sonarqube:
  script:
    - export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64/"
    - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install -Dmaven.test.failure.ignore=false -U -DskipITs -Dgpg.skip
    - mvn --batch-mode verify sonar:sonar -DskipITs -Dgpg.skip
  stage: test-java
  only:
    - master
    - develop
  tags:
    - java10

code_semanticlab_net_deploy:
  script:
    - pwd
    - echo "=================================="
    - export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64/"
    - mvn clean
    - mvn deploy -U -DskipITs -Dgpg.skip
    - echo "=================================="
  stage: deploy
  only:
    - master
  tags:
    - java10
