sonar.projectKey=${env.PROJECT}
sonar.projectName=${env.PROJECT}
sonar.projectVersion=${env.VERSION}
sonar.sources=${env.SRCDIR}
sonar.tests=./src/python/weblyzard_api/tests/
sonar.coverage.exclusions=${env.SRCDIR}/tests/
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test_results.xml
sonar.python.xunit.skipDetails=false
sonar.java.binaries=**/target/classes
