[tox]
envlist = {py37, py38,  py310}

[testenv]
basepython = python3.10
whitelist_externals = poetry
skip_install = true

commands =
    poetry install -vvv
    poetry run pytest --cov tests/
    poetry run pytest tests/
    
setenv = 
    testsdir = {env:TESTSDIR:tests/}
    srcdir = {env:SRCDIR:src/}

deps = 
    pytest
    pytest-cov
    mock
    poetry
    future
    -rrequirements.txt


[testenv:pytest]
# set pip config location? also, sitepackages might not be needed here
sitepackages = True
description = run pytest + list tests

# needed to separate the global install from the local
# deselecting slow tests for the gitlab runner
commands = 
    python -m pytest -v -m 'not slow' \
        --cov-report xml \
        --cov-report term \
        --junitxml test_results.xml \
        --cov={env:PROJECT:} {env:TESTSDIR:tests/}
    python -m pytest -v --collect-only {env:TESTSDIR:tests/}

[testenv:pylint]
description = run pylint and handle it's exit codes (in pylint.sh)

whitelist_externals = 
    /bin/bash

deps = 
    pylint
    pylint-exit

commands = 
    /bin/bash pylint.sh {env:SRCDIR:src/}

[testenv:pytest-slow]
description = run slow pytest tests
sitepackages = True

commands = 
    python -m pytest -v -m 'slow' --cov-report term {env:TESTSDIR:tests/}

[testenv:vulture]
description = run vulture and (hopefully) find dead code 

deps = 
    vulture

commands = 
    python -m vulture {env:SRCDIR:src/} {env:TESTSDIR:tests/}

[testenv:pipdeptree]
description = run pipdeptree
sitepackages = False

deps = 
    pipdeptree

commands =
    python -m pipdeptree -fl

[testenv:audit]
description = list outdated packages and audit packages
sitepackages = False

deps =
    pip-audit

commands =
    python -m pip list --outdated
    python -m pip_audit
